#ifndef __System_System_H__
#define __System_System_H__

//+ includes
#include <stdio.h>
#include "Thunk.h"
//+
//#include "System.1\Object.h"
//#include "System.1\Array.h"
//#include "System.1\Array\FunctorComparer.h"
#include "System.1\Boolean.h"
//#include "System.1\Byte.h"
//#include "System.1\Char.h"
//#include "System.1\DateTime.h"
//#include "System.1\Decimal.h"
//#include "System.1\Double.h"
//#include "System.1\Int16.h"
//#include "System.1\Int32.h"
//#include "System.1\Int64.h"
//#include "System.1\SByte.h"
//#include "System.1\Single.h"
//#include "System.1\String.h"
//#include "System.1\UInt16.h"
//#include "System.1\UInt32.h"
//#include "System.1\UInt64.h"
//#include "System.2\ICloneable.h"
//#include "System.2\IComparable.h"
//#include "System.2\IDisposable.h"
//#include "System.2\Action.h"
//#include "System.2\Comparison.h"
//#include "System.2\Predicate.h"
//#include "Collections\IArraySortHelper.h"
//#include "Collections\IArraySortHelper2.h"
//#include "Collections\IComparer.h"
//#include "Collections\IEnumerator.h"
//#include "Collections\IEnumerable.h"
//#include "Collections\IEqualityComparer.h"
//#include "Collections\Comparer.h"
//#include "Collections\GenericComparer.h"
//#include "Collections\EqualityComparer.h"
//#include "Collections.1\ICollection.h"
//#include "Collections.1\IDictionary.h"
//#include "Collections.1\IList.h"
//#include "Collections.1\Dictionary.h"
//#include "Collections.1\KeyValuePair.h"
//#include "Collections.1\List.h"
//#include "Collections.2\LinkedList.h"
//#include "Collections.2\LinkedListNode.h"
//#include "Collections.2\SortedDictionary.h"
//
//#include "SystemT.h"
//#include "System.1\Array\SZArrayEnumerator.h"
//Declare_System(System_Object, object)

#endif /* __System_System_H__ */
